# Generated by Django 4.0 on 2021-12-29 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='option_four',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='option_one',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='option_three',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='option_two',
        ),
    ]
