# Generated by Django 4.0 on 2021-12-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0003_question_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='image',
            new_name='image_file',
        ),
        migrations.AddField(
            model_name='question',
            name='image_url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
