# Generated by Django 4.0 on 2021-12-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0004_rename_image_question_image_file_question_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image_url',
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(default=' ', upload_to='quiz/images'),
        ),
    ]
