# Generated by Django 4.0 on 2021-12-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0005_remove_question_image_file_remove_question_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='schedul_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Quiz_date'),
        ),
    ]
