# Generated by Django 4.0 on 2021-12-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0008_alter_course_schedul_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='schedul_date',
            field=models.DateTimeField(null=True),
        ),
    ]
